CREATE TABLE GAB_4110_CUST_BDGT(
CUSTOMER CHAR(6),
YEAR INT,
BDGT_JAN FLOAT,
BDGT_FEB FLOAT,
BDGT_MAR FLOAT,
BDGT_APR FLOAT,
BDGT_MAY FLOAT,
BDGT_JUN FLOAT,
BDGT_JUL FLOAT,
BDGT_AUG FLOAT,
BDGT_SEP FLOAT,
BDGT_OCT FLOAT,
BDGT_NOV FLOAT,
BDGT_DEC FLOAT
);